# version: '3.8'

services:
  aloud-db:
    image: postgres:15-alpine
    container_name: aloud_postgres
    restart: always
    environment:
      POSTGRES_DB: aloud_dev
      POSTGRES_USER: alouduser
      POSTGRES_PASSWORD: aloudpassword123
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: