"""Add reading table to the database for saving stats

Revision ID: 92292257bda8
Revises: e41769e89945
Create Date: 2026-06-03 14:01:42.398891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92292257bda8'
down_revision = 'e41769e89945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(length=60), nullable=False),
    sa.Column('total_reads', sa.Integer(), nullable=False),
    sa.Column('today_reads', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    # ### end Alembic commands ###
